### ISSUE TITLE
Quizz-1 - For loop

### ISSUE THREAD

**Issue by db0sch** [lewagon/quizzes#10]
Do we really want to keep the For loop example in the Quizz...
As we tell the students not to use it during lectures.

What do you think of asking the student to mention the For loop (just to check he knows it), and ask him to write the grade average loop with `#each` ?

Some of our student didn't even respond to the question as they didn't even bother to learn it as we told them not to use it, and prefer `#each` instead.

**Comment by ssaunier** [comment]
I feel like the `for` loop is still very important as it's ubiquitous in every language. The next question in the quizz ask for the prefer idiom so in the end they still get to answer #each. I feel like they should know that a pillar of programming language is a `for` loop, and the conclusion that they don't learn something only because we tell them it's not used often (not never!), well I don't like it ;)

**Comment by db0sch** [comment]
🙆‍♂️
